import React, { useState, useEffect } from 'react';
import BlockWidgetWrapper from '@layout/BlockWidgetWrapper';
import type { BlockWidgetWrapperProps } from '@layout/BlockWidgetWrapper';
import type { FAQAccordionBlock } from './schema';
import { FAQ_ACCORDION_ITEM_LIMIT } from './schema';
import { useSelection } from '@context/SelectionContext';
import { useBlockEditing } from '@context/BlockEditingContext';
import BlockItemControl from '@layout/BlockItemControl';
import { ChevronDown, ChevronRight, HelpCircle } from 'lucide-react';

interface FAQAccordionWidgetProps extends Omit<BlockWidgetWrapperProps<FAQAccordionBlock>, 'block'> {
  block: FAQAccordionBlock;
}

export const FAQAccordionWidget: React.FC<FAQAccordionWidgetProps> = ({
  block,
  onSelect,
  isSelected = false,
  canMoveUp,
  canMoveDown,
  onMoveUp,
  onMoveDown,
  onDuplicate,
  onRemove,
}) => {
  const { title, items, default_open_index } = block.props;
  const { style } = block;

  const [openIndex, setOpenIndex] = useState(default_open_index ?? -1);
  const { selectBlockItem, isItemSelected } = useSelection();
  const { addBlockItem, moveBlockItemUp, moveBlockItemDown, removeBlockItem } = useBlockEditing();

  useEffect(() => {
    setOpenIndex(default_open_index ?? -1);
  }, [default_open_index]);

  const handleAddItem = () => {
    const currentItemCount = items?.length || 0;

    if (currentItemCount >= FAQ_ACCORDION_ITEM_LIMIT) {
      return; // Don't add more items if at limit
    }

    const defaultItem = {
      id: '', // Will be generated by addBlockItem
      question: 'New Question',
      answer: 'New Answer',
      style: {
        background_color: '#1f2937',
        text_color: '#ffffff',
        font_weight: 'normal' as const,
        padding: 'sm' as const,
        margin: 'md' as const,
        border_radius: 'md' as const,
      },
    };

    const newId = addBlockItem(block.id, defaultItem);
    selectBlockItem(block.id, newId);
  };

  const handleQuestionClick = (e: React.MouseEvent, itemId: string, index: number) => {
    e.stopPropagation();

    // First, select the item
    selectBlockItem(block.id, itemId);

    // Then, toggle the accordion
    setOpenIndex(index === openIndex ? -1 : index);
  };

  // Check if we're at the item limit
  const isAtItemLimit = (items?.length || 0) >= FAQ_ACCORDION_ITEM_LIMIT;

  const textAlignClass = style?.text_align === 'center' ? 'text-center' :
    style?.text_align === 'right' ? 'text-right' : 'text-left';

  // Handle text color - if it's a hex value, use inline style, otherwise use Tailwind class
  const isHexColor = style?.text_color && style.text_color.startsWith('#');

  // Determine background styling
  const hasCustomBackground = !!style?.background_color;
  const defaultBackgroundClass = 'bg-black';
  const backgroundClass = hasCustomBackground ? '' : defaultBackgroundClass;

  // Style value mappings for cleaner code - reduced padding values
  const borderRadiusMap = {
    none: '0',
    sm: '0.25rem',
    md: '0.5rem',
    lg: '1rem',
  };



  // Handle box shadow - custom CSS values for better visibility on dark backgrounds
  const getBoxShadowStyle = (shadowType: string | undefined) => {
    switch (shadowType) {
      case 'lg': return '0 20px 25px -5px rgba(255, 255, 255, 0.3), 0 10px 10px -5px rgba(255, 255, 255, 0.2)';
      case 'md': return '0 10px 15px -3px rgba(255, 255, 255, 0.3), 0 4px 6px -2px rgba(255, 255, 255, 0.2)';
      case 'sm': return '0 4px 6px -1px rgba(255, 255, 255, 0.3), 0 2px 4px -1px rgba(255, 255, 255, 0.2)';
      default: return undefined;
    }
  };
  const boxShadowStyle = getBoxShadowStyle(style?.box_shadow ?? 'none');

  const itemPaddingMap = {
    sm: '0.75rem',
    md: '1rem',
    lg: '1.25rem',
  };

  const itemMarginMap = {
    sm: '0.25rem',
    md: '0.5rem',
    lg: '1rem',
  };

  // Build complete style object for BlockWidgetWrapper - this applies to the main container
  // Build complete style object for BlockWidgetWrapper - this applies to the main container
  const widgetStyle: React.CSSProperties = {
    backgroundColor: hasCustomBackground ? style.background_color : undefined,
    color: isHexColor ? style.text_color : undefined,
    borderRadius: style?.border_radius ? borderRadiusMap[style.border_radius] : undefined,
    maxWidth: style?.max_width || undefined,
    paddingTop: style?.padding_top,
    paddingRight: style?.padding_right,
    paddingBottom: style?.padding_bottom,
    paddingLeft: style?.padding_left,
    marginTop: style?.margin_top,
    marginRight: style?.margin_right,
    marginBottom: style?.margin_bottom,
    marginLeft: style?.margin_left,
  };

  if (!items || items.length === 0) {
    return (
      <div style={{ boxShadow: boxShadowStyle }}>
        <BlockWidgetWrapper
          block={block}
          onSelect={onSelect}
          isSelected={isSelected}
          canMoveUp={canMoveUp}
          canMoveDown={canMoveDown}
          onMoveUp={onMoveUp}
          onMoveDown={onMoveDown}
          onDuplicate={onDuplicate}
          onRemove={onRemove}
          onAddItem={!isAtItemLimit ? handleAddItem : undefined}
          className={`${backgroundClass} ${textAlignClass}`}
          style={widgetStyle}
        >
          <div className="faq-accordion">
            {title && (
              <h3
                className="text-2xl font-bold mb-6"
                style={{ color: style?.text_color || undefined }}
              >
                {title}
              </h3>
            )}

            <div className="text-center py-8 text-gray-500 border-2 border-dashed border-gray-300 rounded-lg">
              <p className="mb-2">No FAQ items yet</p>
              <p className="text-sm">Click the + button to add your first FAQ (max {FAQ_ACCORDION_ITEM_LIMIT} items)</p>
            </div>
          </div>
        </BlockWidgetWrapper>
      </div>
    );
  }

  return (
    <div style={{ boxShadow: boxShadowStyle }}>
      <BlockWidgetWrapper
        block={block}
        onSelect={onSelect}
        isSelected={isSelected}
        canMoveUp={canMoveUp}
        canMoveDown={canMoveDown}
        onMoveUp={onMoveUp}
        onMoveDown={onMoveDown}
        onDuplicate={onDuplicate}
        onRemove={onRemove}
        onAddItem={!isAtItemLimit ? handleAddItem : undefined}
        className={`${backgroundClass} ${textAlignClass}`}
        style={widgetStyle}
      >
        <div className="faq-accordion">
          {title && (
            <h3
              className="text-2xl font-bold mb-6"
              style={{ color: style?.text_color || undefined }}
            >
              {title}
            </h3>
          )}

          <div className="space-y-2">
            {items.map((item, index) => {
              // Build item-specific styles using mappings
              const itemStyle: React.CSSProperties = {
                backgroundColor: item.style?.background_color || undefined,
                color: item.style?.text_color || undefined,
                padding: item.style?.padding ? itemPaddingMap[item.style.padding] : undefined,
                margin: item.style?.margin ? itemMarginMap[item.style.margin] : undefined,
                borderRadius: item.style?.border_radius ? borderRadiusMap[item.style.border_radius] : undefined,
                boxShadow: getBoxShadowStyle(item.style?.box_shadow ?? 'none'),
              };

              const isSelected = isItemSelected(block.id, item.id);
              return (
                <div
                  key={item.id}
                  className={`
                  border border-gray-700 overflow-hidden relative group
                  ${isSelected ? 'ring-2 ring-blue-500 ring-offset-2 ring-offset-black' : ''}
                  cursor-pointer
                `}
                  style={{
                    ...itemStyle,
                    // Remove box shadow when selected to let selection ring show
                    boxShadow: isSelected ? undefined : itemStyle.boxShadow,
                  }}
                  onClick={(e) => handleQuestionClick(e, item.id, index)}
                >
                  <div
                    className={`
                    w-full text-left flex items-center justify-between
                    transition-all duration-200
                    ${item.style?.font_weight === 'bold' ? 'font-bold' : 'font-normal'}
                  `}
                    style={{
                      backgroundColor: item.style?.background_color || undefined,
                      color: item.style?.text_color || undefined,
                    }}
                  >
                    <div className="flex items-center gap-3">
                      <HelpCircle size={18} className="text-gray-300 flex-shrink-0" />
                      <span className="text-lg">{item.question}</span>
                    </div>

                    <div className="flex-shrink-0">
                      {openIndex === index ? (
                        <ChevronDown size={20} className="text-gray-300 flex-shrink-0" />
                      ) : (
                        <ChevronRight size={20} className="text-gray-300 flex-shrink-0" />
                      )}
                    </div>
                  </div>

                  {openIndex === index && (
                    <div
                      id={`faq-answer-${item.id}`}
                      className="px-4 pb-4"
                      style={{
                        backgroundColor: item.style?.background_color || '#111827',
                        color: item.style?.text_color || undefined,
                      }}
                    >
                      <div className="pt-2 leading-relaxed">
                        {item.answer}
                      </div>
                    </div>
                  )}

                  {/* Item Controls - visible on hover and when selected */}
                  <BlockItemControl
                    index={index}
                    count={items.length}
                    onMoveUp={() => moveBlockItemUp(block.id, index)}
                    onMoveDown={() => moveBlockItemDown(block.id, index)}
                    onRemove={() => removeBlockItem(block.id, item.id)}
                    className="absolute top-2 right-10 flex space-x-1 bg-white/95 rounded-lg p-1 shadow-lg opacity-0 group-hover:opacity-100 transition-opacity duration-200 z-10"
                  />
                </div>
              );
            })}
          </div>
        </div>
      </BlockWidgetWrapper>
    </div>
  );
};

export default FAQAccordionWidget; 